### ISSUE TITLE
Radioq display

### ISSUE THREAD

**Issue by ocots** [jverzani/QuizQuestions.jl#53]
Hi @jverzani!

Thank you for the package. I have started to use it to make a course about Julia. 

I have a question if possible. When we use the `radioq` function and click on a radio button, the text below go down. I found that it would be better the pop-up appearing without moving the text below. 

What do you think?

Here is what I mean:

<img width="1091" alt="Capture d’écran 2024-11-09 à 21 16 49" src="https://github.com/user-attachments/assets/ee485785-5c45-4e04-8810-e6560487b762">

**Comment by ocots** [comment]
Actually I have made some modifications in my css:

```css
div[id$='_message']{
  height:20px;
  width:120px;
  padding-bottom: 0px !important;
  margin-top: 10px!important;
}

div[id$='_message'] .admonition{
  padding:5px!important;
  padding-left: 10px!important;
  border-radius: 5px;
  margin-left: 20px;
}
```

Here is the result: https://ocots.github.io/course-tse-julia-M1/M1/advanced-types.html#quiz

ps: do not read the questions I have made them with ChatGPT and I haven't red them yet.
